name: Check Visa Timestamp

on:
  schedule:
    - cron: '12,42 * * * *' # Toutes les 30 minutes, en évitant les pics de charge des heures rondes
  workflow_dispatch:
    inputs:
      force_email:
        description: 'Forcer l envoi du mail de test ?'
        required: true
        default: false
        type: boolean

jobs:
  check-timestamp:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Passage en v4 (plus récent)

    - name: Setup Node.js
      uses: actions/setup-node@v4 # Passage en v4
      with:
        node-version: '20' # <--- C'EST LA CORRECTION CRITIQUE (18 -> 20)

    - name: Install dependencies
      run: npm install

    - name: Run script
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
        FORCE_EMAIL: ${{ inputs.force_email }}
      run: node index.js

    - name: Commit and push if changed
      run: |
        git config --global user.name 'Visa Bot'
        git config --global user.email 'bot@noreply.github.com'
        git add .
        # Ne commit que s'il y a un changement, sinon ne fait rien
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update signature" && git push)
